### ISSUE TITLE
Document removal of 'empty' rows before submission

### ISSUE THREAD

**Issue by ychae** [ncihtan/HTAN-Data-Ingress-Docs#24]
Moving ticket https://github.com/Sage-Bionetworks/DCA-Data-Ingress-Docs/issues/22 to this repo:

From @adamjtaylor:

> Per [HTAN-92](https://sagebionetworks.jira.com/browse/HTAN-92), we should clarify that if metadata is being submitted/resubmitted for only some entities, "empty rows" - those containing just a file name and entityId should be removed from the csv before upload and validation - otherwise validation will fail.
This does not appear to be documented in the FAQ so far.

**Comment by milen-sage** [comment]
PR approved #28.  

@aclayton555 just a note, we are automating the build and deployment of documentation so that it's easier to make content changes to it in the future. We can always help, but when it's easier to make changes on the project-side, it'd speed up addressing doc issues. Will keep you updated over the next month or so.
