### ISSUE TITLE
Document how to get an empty template

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/HTAN-Data-Ingress-Docs#25]
Per slack conversation with HMS: https://htanworkspace.slack.com/archives/G01GE48M8UA/p1657049766750599

**Comment by linglp** [comment]
@milen-sage Could you give me access to the slack channel?

**Comment by milen-sage** [comment]
You should have access now. But essentially, it's outlining that one can generate an empty template for a dataset w/o existing files in it.

To generate a template w/o filling in existing filenames, the user can create an empty dataset folder, go to the DCA, select this folder, and generate a template for it; they may see a warning that there are no files, but they can ignore the warning and still get the template.

We can add the relevant schematic command as well, if they'd like to do this programmatically. A notebook showing how they can do that (e.g. to generate one or multiple templates at once) could be great to link.

**Comment by linglp** [comment]
More information: 
1. Access DCA by using the demo instance: https://sagebio.shinyapps.io/data_curator-testing2/
2. Create a fork of Bruno's fork repo under SageBionetworks. See Bruno's fork repo here: https://github.com/BrunoGrandePhD/HTAN-Data-Ingress-Docs/tree/develop-generic-docs
3. Rename the new repo as "data curator doc". 
4. After making changes to generic repo, create a pull request to HTAN so that they could pull from generic docs

**Comment by linglp** [comment]
@milen-sage I noticed that under Sage Bionetworks, there's already one repo [here](https://github.com/Sage-Bionetworks/DCA-Data-Ingress-Docs) for Data-Ingress-Docs. Should I just create a separate branch for HTAN instead of creating a brand new repo? I also can't fork Bruno's repo and have it under Sage Bionetworks because that repo already exists.

**Comment by milen-sage** [comment]
Ah I see - yes, this makes sense :)

Let's just reuse this repo with a new branch and keep the branch(es) generic though - not HTAN-specific.  We can follow the code contribution guidelines for branch naming and PRs. We can still setup the repo the way @BrunoGrandePhD has it in his fork.
